apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-api
  labels:
    app: movie-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
      containers:
      - name: movie-api
        image: oopsaman/movie_api:latest
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: movie-api-service
  labels:
    app: movie-api
spec:
  selector:
    app: movie-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer